### ISSUE TITLE
Faceit / esea radarhack

### ISSUE THREAD

**Issue by burmalda66699** [NoSkill33/CSGO-Cheat-Loader#1]
Hello,
How do you think, is it possible for you to make an undetected radarhack for faceit and esea anticheats and how much it could be worth?

**Comment by NoSkill33** [comment]
> Hello,
> 
> How do you think, is it possible for you to make an undetected radarhack for faceit and esea anticheats and how much it could be worth?

Yes it is possible to make undetected radar hack for both of anti cheats. I don't know the price of it.
